/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'etqw.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _GUID;
struct TypeDescriptor;
struct HINSTANCE__;
struct IDispatch;
struct ITypeInfo;
struct ITypeInfoVtbl;
struct tagTYPEATTR;
struct tagTYPEDESC;
struct tagARRAYDESC;
struct ITypeComp;
struct ITypeCompVtbl;
union tagBINDPTR;
struct tagFUNCDESC;
struct tagELEMDESC;
struct tagPARAMDESCEX;
struct tagVARIANT;
struct IUnknown;
struct IUnknownVtbl;
struct tagSAFEARRAY;
struct tagDEC;
struct IRecordInfo;
struct IRecordInfoVtbl;
struct tagVARDESC;
struct tagDISPPARAMS;
struct tagEXCEPINFO;
struct ITypeLib;
struct ITypeLibVtbl;
struct tagTLIBATTR;
struct _s_ThrowInfo;
struct _s_CatchableTypeArray;
struct _s_CatchableType;
struct HDC__;
struct HWND__;
struct tagWNDCLASSEXA;
struct HICON__;
struct HBRUSH__;
struct _CONTEXT;
union _LARGE_INTEGER;
struct HKEY__;
struct _SHELLEXECUTEINFOA;
struct _IP_ADDR_STRING;
struct $F03B70C123AB6920C4DDA521DD856E56;
struct tagWNDCLASSA;
struct tagPIXELFORMATDESCRIPTOR;
struct _devicemodeA;
struct HMONITOR__;
struct HIMC__;
struct _PDH_FMT_COUNTERVALUE;
struct tagCANDIDATELIST;
struct HKL__;
struct _RTL_CRITICAL_SECTION;
struct _RTL_CRITICAL_SECTION_DEBUG;
struct _EXCEPTION_RECORD;
struct HBITMAP__;
struct tagRAWINPUTDEVICE;
struct _XINPUT_STATE;
struct _XINPUT_CAPABILITIES;

/* 1 */
typedef struct _GUID GUID;

/* 2 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 3 */
enum __bitmask __TI_flags
{
  TI_IsConst = 0x1,
  TI_IsVolatile = 0x2,
  TI_IsUnaligned = 0x4,
  TI_IsPure = 0x8,
  TI_IsWinRT = 0x10,
};

/* 4 */
enum __bitmask __CT_flags
{
  CT_IsSimpleType = 0x1,
  CT_ByReferenceOnly = 0x2,
  CT_HasVirtualBase = 0x4,
  CT_IsWinRTHandle = 0x8,
  CT_IsStdBadAlloc = 0x10,
};

/* 5 */
struct FuncInfo
{
  unsigned __int32 magicNumber : 29;
  unsigned __int32 bbtFlags : 3;
  int maxState __dec;
  void *pUnwindMap;
  int nTryBlocks __dec;
  void *pTryBlockMap;
  int nIPMapEntries __dec;
  void *pIPtoStateMap;
  void *pESTypeList;
  int EHFlags __hex;
};

/* 6 */
struct UnwindMapEntry
{
  int toState __dec;
  void *action;
};

/* 7 */
struct TryBlockMapEntry
{
  int tryLow __dec;
  int tryHigh __dec;
  int catchHigh __dec;
  int nCatches __dec;
  void *pHandlerArray;
};

/* 8 */
struct HandlerType
{
  int adjectives __hex;
  const struct TypeDescriptor *pType;
  int dispCatchObj __dec;
  void *addressOfHandler;
};

/* 9 */
struct TypeDescriptor
{
  const struct TypeDescriptor_vtbl *__vftable /*VFT*/;
  void *spare;
  char name[] __strlit(C,"windows-1252");
};

/* 10 */
struct _SCOPETABLE_ENTRY
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 11 */
typedef void *PVOID;

/* 12 */
typedef unsigned int DWORD;

/* 13 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 14 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 15 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 16 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 17 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 18 */
struct _EH4_SCOPETABLE_RECORD
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 19 */
struct _EH4_SCOPETABLE
{
  DWORD GSCookieOffset;
  DWORD GSCookieXOROffset;
  DWORD EHCookieOffset;
  DWORD EHCookieXOROffset;
  struct _EH4_SCOPETABLE_RECORD ScopeRecord[];
};

/* 20 */
typedef unsigned int size_t;

/* 21 */
typedef struct HINSTANCE__ *HINSTANCE;

/* 22 */
struct HINSTANCE__
{
  int unused;
};

/* 23 */
typedef __int64 __time64_t;

/* 25 */
typedef unsigned int ULONG_PTR;

/* 28 */
typedef void *HANDLE;

/* 24 */
struct _OVERLAPPED
{
  ULONG_PTR Internal;
  ULONG_PTR InternalHigh;
  union
  {
    struct
    {
      DWORD Offset;
      DWORD OffsetHigh;
    };
    PVOID Pointer;
  };
  HANDLE hEvent;
};

/* 30 */
typedef char CHAR;

/* 29 */
typedef const CHAR *LPCSTR;

/* 34 */
typedef int HRESULT;

/* 33 */
typedef GUID IID;

/* 35 */
typedef unsigned int ULONG;

/* 36 */
typedef unsigned int UINT;

/* 37 */
typedef DWORD LCID;

/* 48 */
typedef unsigned __int16 wchar_t;

/* 47 */
typedef wchar_t WCHAR;

/* 46 */
typedef WCHAR OLECHAR;

/* 45 */
typedef OLECHAR *LPOLESTR;

/* 44 */
typedef int LONG;

/* 43 */
typedef LONG DISPID;

/* 51 */
typedef unsigned __int16 WORD;

/* 124 */
typedef struct tagDISPPARAMS DISPPARAMS;

/* 80 */
typedef struct tagVARIANT VARIANT;

/* 126 */
typedef struct tagEXCEPINFO EXCEPINFO;

/* 31 */
#pragma pack(push, 8)
struct IDispatchVtbl
{
  HRESULT (__stdcall *QueryInterface)(IDispatch *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(IDispatch *This);
  ULONG (__stdcall *Release)(IDispatch *This);
  HRESULT (__stdcall *GetTypeInfoCount)(IDispatch *This, UINT *pctinfo);
  HRESULT (__stdcall *GetTypeInfo)(IDispatch *This, UINT iTInfo, LCID lcid, ITypeInfo **ppTInfo);
  HRESULT (__stdcall *GetIDsOfNames)(IDispatch *This, const IID *const riid, LPOLESTR *rgszNames, UINT cNames, LCID lcid, DISPID *rgDispId);
  HRESULT (__stdcall *Invoke)(IDispatch *This, DISPID dispIdMember, const IID *const riid, LCID lcid, WORD wFlags, DISPPARAMS *pDispParams, VARIANT *pVarResult, EXCEPINFO *pExcepInfo, UINT *puArgErr);
};
#pragma pack(pop)

/* 32 */
#pragma pack(push, 8)
struct IDispatch
{
  struct IDispatchVtbl *lpVtbl;
};
#pragma pack(pop)

/* 38 */
#pragma pack(push, 8)
struct ITypeInfo
{
  struct ITypeInfoVtbl *lpVtbl;
};
#pragma pack(pop)

/* 79 */
typedef VARIANT VARIANTARG;

/* 125 */
#pragma pack(push, 8)
struct tagDISPPARAMS
{
  VARIANTARG *rgvarg;
  DISPID *rgdispidNamedArgs;
  UINT cArgs;
  UINT cNamedArgs;
};
#pragma pack(pop)

/* 60 */
typedef unsigned __int16 VARTYPE;

/* 85 */
typedef __int64 LONGLONG;

/* 86 */
typedef unsigned __int8 BYTE;

/* 87 */
typedef __int16 SHORT;

/* 88 */
typedef float FLOAT;

/* 89 */
typedef double DOUBLE;

/* 90 */
typedef __int16 VARIANT_BOOL;

/* 71 */
typedef LONG SCODE;

/* 92 */
union tagCY
{
  struct
  {
    ULONG Lo;
    LONG Hi;
  };
  LONGLONG int64;
};

/* 91 */
typedef union tagCY CY;

/* 94 */
typedef double DATE;

/* 95 */
typedef OLECHAR *BSTR;

/* 98 */
typedef struct tagSAFEARRAY SAFEARRAY;

/* 56 */
typedef unsigned __int16 USHORT;

/* 100 */
typedef unsigned __int64 ULONGLONG;

/* 101 */
typedef int INT;

/* 102 */
typedef struct tagDEC DECIMAL;

/* 103 */
struct tagDEC
{
  USHORT wReserved;
  union
  {
    struct
    {
      BYTE scale;
      BYTE sign;
    };
    USHORT signscale;
  };
  ULONG Hi32;
  union
  {
    struct
    {
      ULONG Lo32;
      ULONG Mid32;
    };
    ULONGLONG Lo64;
  };
};

/* 81 */
#pragma pack(push, 8)
struct tagVARIANT
{
  #pragma pack(push, 8)
  union
  {
    #pragma pack(push, 8)
    struct
    {
      VARTYPE vt;
      WORD wReserved1;
      WORD wReserved2;
      WORD wReserved3;
      #pragma pack(push, 8)
      union
      {
        LONGLONG llVal;
        LONG lVal;
        BYTE bVal;
        SHORT iVal;
        FLOAT fltVal;
        DOUBLE dblVal;
        VARIANT_BOOL boolVal;
        SCODE scode;
        CY cyVal;
        DATE date;
        BSTR bstrVal;
        IUnknown *punkVal;
        IDispatch *pdispVal;
        SAFEARRAY *parray;
        BYTE *pbVal;
        SHORT *piVal;
        LONG *plVal;
        LONGLONG *pllVal;
        FLOAT *pfltVal;
        DOUBLE *pdblVal;
        VARIANT_BOOL *pboolVal;
        SCODE *pscode;
        CY *pcyVal;
        DATE *pdate;
        BSTR *pbstrVal;
        IUnknown **ppunkVal;
        IDispatch **ppdispVal;
        SAFEARRAY **pparray;
        VARIANT *pvarVal;
        PVOID byref;
        CHAR cVal;
        USHORT uiVal;
        ULONG ulVal;
        ULONGLONG ullVal;
        INT intVal;
        UINT uintVal;
        DECIMAL *pdecVal;
        CHAR *pcVal;
        USHORT *puiVal;
        ULONG *pulVal;
        ULONGLONG *pullVal;
        INT *pintVal;
        UINT *puintVal;
        #pragma pack(push, 8)
        struct
        {
          PVOID pvRecord;
          IRecordInfo *pRecInfo;
        };
        #pragma pack(pop)
      };
      #pragma pack(pop)
    };
    #pragma pack(pop)
    DECIMAL decVal;
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 127 */
#pragma pack(push, 8)
struct tagEXCEPINFO
{
  WORD wCode;
  WORD wReserved;
  BSTR bstrSource;
  BSTR bstrDescription;
  BSTR bstrHelpFile;
  DWORD dwHelpContext;
  PVOID pvReserved;
  HRESULT (__stdcall *pfnDeferredFillIn)(struct tagEXCEPINFO *);
  SCODE scode;
};
#pragma pack(pop)

/* 40 */
typedef struct tagTYPEATTR TYPEATTR;

/* 69 */
typedef struct tagFUNCDESC FUNCDESC;

/* 119 */
typedef struct tagVARDESC VARDESC;

/* 42 */
typedef DISPID MEMBERID;

/* 59 */
typedef DWORD HREFTYPE;

/* 116 */
enum __bitmask tagINVOKEKIND
{
  INVOKE_FUNC = 0x1,
  INVOKE_PROPERTYGET = 0x2,
  INVOKE_PROPERTYPUT = 0x4,
  INVOKE_PROPERTYPUTREF = 0x8,
};

/* 115 */
typedef enum tagINVOKEKIND INVOKEKIND;

/* 39 */
#pragma pack(push, 8)
struct ITypeInfoVtbl
{
  HRESULT (__stdcall *QueryInterface)(ITypeInfo *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(ITypeInfo *This);
  ULONG (__stdcall *Release)(ITypeInfo *This);
  HRESULT (__stdcall *GetTypeAttr)(ITypeInfo *This, TYPEATTR **ppTypeAttr);
  HRESULT (__stdcall *GetTypeComp)(ITypeInfo *This, ITypeComp **ppTComp);
  HRESULT (__stdcall *GetFuncDesc)(ITypeInfo *This, UINT index, FUNCDESC **ppFuncDesc);
  HRESULT (__stdcall *GetVarDesc)(ITypeInfo *This, UINT index, VARDESC **ppVarDesc);
  HRESULT (__stdcall *GetNames)(ITypeInfo *This, MEMBERID memid, BSTR *rgBstrNames, UINT cMaxNames, UINT *pcNames);
  HRESULT (__stdcall *GetRefTypeOfImplType)(ITypeInfo *This, UINT index, HREFTYPE *pRefType);
  HRESULT (__stdcall *GetImplTypeFlags)(ITypeInfo *This, UINT index, INT *pImplTypeFlags);
  HRESULT (__stdcall *GetIDsOfNames)(ITypeInfo *This, LPOLESTR *rgszNames, UINT cNames, MEMBERID *pMemId);
  HRESULT (__stdcall *Invoke)(ITypeInfo *This, PVOID pvInstance, MEMBERID memid, WORD wFlags, DISPPARAMS *pDispParams, VARIANT *pVarResult, EXCEPINFO *pExcepInfo, UINT *puArgErr);
  HRESULT (__stdcall *GetDocumentation)(ITypeInfo *This, MEMBERID memid, BSTR *pBstrName, BSTR *pBstrDocString, DWORD *pdwHelpContext, BSTR *pBstrHelpFile);
  HRESULT (__stdcall *GetDllEntry)(ITypeInfo *This, MEMBERID memid, INVOKEKIND invKind, BSTR *pBstrDllName, BSTR *pBstrName, WORD *pwOrdinal);
  HRESULT (__stdcall *GetRefTypeInfo)(ITypeInfo *This, HREFTYPE hRefType, ITypeInfo **ppTInfo);
  HRESULT (__stdcall *AddressOfMember)(ITypeInfo *This, MEMBERID memid, INVOKEKIND invKind, PVOID *ppv);
  HRESULT (__stdcall *CreateInstance)(ITypeInfo *This, IUnknown *pUnkOuter, const IID *const riid, PVOID *ppvObj);
  HRESULT (__stdcall *GetMops)(ITypeInfo *This, MEMBERID memid, BSTR *pBstrMops);
  HRESULT (__stdcall *GetContainingTypeLib)(ITypeInfo *This, ITypeLib **ppTLib, UINT *pIndex);
  void (__stdcall *ReleaseTypeAttr)(ITypeInfo *This, TYPEATTR *pTypeAttr);
  void (__stdcall *ReleaseFuncDesc)(ITypeInfo *This, FUNCDESC *pFuncDesc);
  void (__stdcall *ReleaseVarDesc)(ITypeInfo *This, VARDESC *pVarDesc);
};
#pragma pack(pop)

/* 96 */
#pragma pack(push, 8)
struct IUnknown
{
  struct IUnknownVtbl *lpVtbl;
};
#pragma pack(pop)

/* 58 */
#pragma pack(push, 8)
struct tagSAFEARRAYBOUND
{
  ULONG cElements;
  LONG lLbound;
};
#pragma pack(pop)

/* 57 */
typedef struct tagSAFEARRAYBOUND SAFEARRAYBOUND;

/* 99 */
#pragma pack(push, 8)
struct tagSAFEARRAY
{
  USHORT cDims;
  USHORT fFeatures;
  ULONG cbElements;
  ULONG cLocks;
  PVOID pvData;
  SAFEARRAYBOUND rgsabound[1];
};
#pragma pack(pop)

/* 109 */
#pragma pack(push, 8)
struct IRecordInfo
{
  struct IRecordInfoVtbl *lpVtbl;
};
#pragma pack(pop)

/* 50 */
enum tagTYPEKIND
{
  TKIND_ENUM = 0x0,
  TKIND_RECORD = 0x1,
  TKIND_MODULE = 0x2,
  TKIND_INTERFACE = 0x3,
  TKIND_DISPATCH = 0x4,
  TKIND_COCLASS = 0x5,
  TKIND_ALIAS = 0x6,
  TKIND_UNION = 0x7,
  TKIND_MAX = 0x8,
};

/* 49 */
typedef enum tagTYPEKIND TYPEKIND;

/* 53 */
#pragma pack(push, 8)
struct tagTYPEDESC
{
  #pragma pack(push, 8)
  union
  {
    struct tagTYPEDESC *lptdesc;
    struct tagARRAYDESC *lpadesc;
    HREFTYPE hreftype;
  };
  #pragma pack(pop)
  VARTYPE vt;
};
#pragma pack(pop)

/* 52 */
typedef struct tagTYPEDESC TYPEDESC;

/* 62 */
#pragma pack(push, 8)
struct tagIDLDESC
{
  ULONG_PTR dwReserved;
  USHORT wIDLFlags;
};
#pragma pack(pop)

/* 61 */
typedef struct tagIDLDESC IDLDESC;

/* 41 */
#pragma pack(push, 8)
struct tagTYPEATTR
{
  GUID guid;
  LCID lcid;
  DWORD dwReserved;
  MEMBERID memidConstructor;
  MEMBERID memidDestructor;
  LPOLESTR lpstrSchema;
  ULONG cbSizeInstance;
  TYPEKIND typekind;
  WORD cFuncs;
  WORD cVars;
  WORD cImplTypes;
  WORD cbSizeVft;
  WORD cbAlignment;
  WORD wTypeFlags;
  WORD wMajorVerNum;
  WORD wMinorVerNum;
  TYPEDESC tdescAlias;
  IDLDESC idldescType;
};
#pragma pack(pop)

/* 63 */
#pragma pack(push, 8)
struct ITypeComp
{
  struct ITypeCompVtbl *lpVtbl;
};
#pragma pack(pop)

/* 72 */
typedef struct tagELEMDESC ELEMDESC;

/* 114 */
enum tagFUNCKIND
{
  FUNC_VIRTUAL = 0x0,
  FUNC_PUREVIRTUAL = 0x1,
  FUNC_NONVIRTUAL = 0x2,
  FUNC_STATIC = 0x3,
  FUNC_DISPATCH = 0x4,
};

/* 113 */
typedef enum tagFUNCKIND FUNCKIND;

/* 118 */
enum tagCALLCONV
{
  CC_FASTCALL = 0x0,
  CC_CDECL = 0x1,
  CC_MSCPASCAL = 0x2,
  CC_PASCAL = 0x2,
  CC_MACPASCAL = 0x3,
  CC_STDCALL = 0x4,
  CC_FPFASTCALL = 0x5,
  CC_SYSCALL = 0x6,
  CC_MPWCDECL = 0x7,
  CC_MPWPASCAL = 0x8,
  CC_MAX = 0x9,
};

/* 117 */
typedef enum tagCALLCONV CALLCONV;

/* 77 */
typedef struct tagPARAMDESCEX *LPPARAMDESCEX;

/* 76 */
#pragma pack(push, 8)
struct tagPARAMDESC
{
  LPPARAMDESCEX pparamdescex;
  USHORT wParamFlags;
};
#pragma pack(pop)

/* 75 */
typedef struct tagPARAMDESC PARAMDESC;

/* 73 */
#pragma pack(push, 8)
struct tagELEMDESC
{
  TYPEDESC tdesc;
  #pragma pack(push, 8)
  union
  {
    IDLDESC idldesc;
    PARAMDESC paramdesc;
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 70 */
#pragma pack(push, 8)
struct tagFUNCDESC
{
  MEMBERID memid;
  SCODE *lprgscode;
  ELEMDESC *lprgelemdescParam;
  FUNCKIND funckind;
  INVOKEKIND invkind;
  CALLCONV callconv;
  SHORT cParams;
  SHORT cParamsOpt;
  SHORT oVft;
  SHORT cScodes;
  ELEMDESC elemdescFunc;
  WORD wFuncFlags;
};
#pragma pack(pop)

/* 123 */
enum tagVARKIND
{
  VAR_PERINSTANCE = 0x0,
  VAR_STATIC = 0x1,
  VAR_CONST = 0x2,
  VAR_DISPATCH = 0x3,
};

/* 122 */
typedef enum tagVARKIND VARKIND;

/* 120 */
#pragma pack(push, 8)
struct tagVARDESC
{
  MEMBERID memid;
  LPOLESTR lpstrSchema;
  #pragma pack(push, 8)
  union
  {
    ULONG oInst;
    VARIANT *lpvarValue;
  };
  #pragma pack(pop)
  ELEMDESC elemdescVar;
  WORD wVarFlags;
  VARKIND varkind;
};
#pragma pack(pop)

/* 128 */
#pragma pack(push, 8)
struct ITypeLib
{
  struct ITypeLibVtbl *lpVtbl;
};
#pragma pack(pop)

/* 97 */
#pragma pack(push, 8)
struct IUnknownVtbl
{
  HRESULT (__stdcall *QueryInterface)(IUnknown *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(IUnknown *This);
  ULONG (__stdcall *Release)(IUnknown *This);
};
#pragma pack(pop)

/* 111 */
typedef const OLECHAR *LPCOLESTR;

/* 112 */
typedef int BOOL;

/* 110 */
#pragma pack(push, 8)
struct IRecordInfoVtbl
{
  HRESULT (__stdcall *QueryInterface)(IRecordInfo *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(IRecordInfo *This);
  ULONG (__stdcall *Release)(IRecordInfo *This);
  HRESULT (__stdcall *RecordInit)(IRecordInfo *This, PVOID pvNew);
  HRESULT (__stdcall *RecordClear)(IRecordInfo *This, PVOID pvExisting);
  HRESULT (__stdcall *RecordCopy)(IRecordInfo *This, PVOID pvExisting, PVOID pvNew);
  HRESULT (__stdcall *GetGuid)(IRecordInfo *This, GUID *pguid);
  HRESULT (__stdcall *GetName)(IRecordInfo *This, BSTR *pbstrName);
  HRESULT (__stdcall *GetSize)(IRecordInfo *This, ULONG *pcbSize);
  HRESULT (__stdcall *GetTypeInfo)(IRecordInfo *This, ITypeInfo **ppTypeInfo);
  HRESULT (__stdcall *GetField)(IRecordInfo *This, PVOID pvData, LPCOLESTR szFieldName, VARIANT *pvarField);
  HRESULT (__stdcall *GetFieldNoCopy)(IRecordInfo *This, PVOID pvData, LPCOLESTR szFieldName, VARIANT *pvarField, PVOID *ppvDataCArray);
  HRESULT (__stdcall *PutField)(IRecordInfo *This, ULONG wFlags, PVOID pvData, LPCOLESTR szFieldName, VARIANT *pvarField);
  HRESULT (__stdcall *PutFieldNoCopy)(IRecordInfo *This, ULONG wFlags, PVOID pvData, LPCOLESTR szFieldName, VARIANT *pvarField);
  HRESULT (__stdcall *GetFieldNames)(IRecordInfo *This, ULONG *pcNames, BSTR *rgBstrNames);
  BOOL (__stdcall *IsMatchingType)(IRecordInfo *This, IRecordInfo *pRecordInfo);
  PVOID (__stdcall *RecordCreate)(IRecordInfo *This);
  HRESULT (__stdcall *RecordCreateCopy)(IRecordInfo *This, PVOID pvSource, PVOID *ppvDest);
  HRESULT (__stdcall *RecordDestroy)(IRecordInfo *This, PVOID pvRecord);
};
#pragma pack(pop)

/* 55 */
#pragma pack(push, 8)
struct tagARRAYDESC
{
  TYPEDESC tdescElem;
  USHORT cDims;
  SAFEARRAYBOUND rgbounds[1];
};
#pragma pack(pop)

/* 66 */
enum tagDESCKIND
{
  DESCKIND_NONE = 0x0,
  DESCKIND_FUNCDESC = 0x1,
  DESCKIND_VARDESC = 0x2,
  DESCKIND_TYPECOMP = 0x3,
  DESCKIND_IMPLICITAPPOBJ = 0x4,
  DESCKIND_MAX = 0x5,
};

/* 65 */
typedef enum tagDESCKIND DESCKIND;

/* 67 */
typedef union tagBINDPTR BINDPTR;

/* 64 */
#pragma pack(push, 8)
struct ITypeCompVtbl
{
  HRESULT (__stdcall *QueryInterface)(ITypeComp *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(ITypeComp *This);
  ULONG (__stdcall *Release)(ITypeComp *This);
  HRESULT (__stdcall *Bind)(ITypeComp *This, LPOLESTR szName, ULONG lHashVal, WORD wFlags, ITypeInfo **ppTInfo, DESCKIND *pDescKind, BINDPTR *pBindPtr);
  HRESULT (__stdcall *BindType)(ITypeComp *This, LPOLESTR szName, ULONG lHashVal, ITypeInfo **ppTInfo, ITypeComp **ppTComp);
};
#pragma pack(pop)

/* 78 */
#pragma pack(push, 8)
struct tagPARAMDESCEX
{
  ULONG cBytes;
  VARIANTARG varDefaultValue;
};
#pragma pack(pop)

/* 130 */
typedef struct tagTLIBATTR TLIBATTR;

/* 129 */
#pragma pack(push, 8)
struct ITypeLibVtbl
{
  HRESULT (__stdcall *QueryInterface)(ITypeLib *This, const IID *const riid, void **ppvObject);
  ULONG (__stdcall *AddRef)(ITypeLib *This);
  ULONG (__stdcall *Release)(ITypeLib *This);
  UINT (__stdcall *GetTypeInfoCount)(ITypeLib *This);
  HRESULT (__stdcall *GetTypeInfo)(ITypeLib *This, UINT index, ITypeInfo **ppTInfo);
  HRESULT (__stdcall *GetTypeInfoType)(ITypeLib *This, UINT index, TYPEKIND *pTKind);
  HRESULT (__stdcall *GetTypeInfoOfGuid)(ITypeLib *This, const GUID *const guid, ITypeInfo **ppTinfo);
  HRESULT (__stdcall *GetLibAttr)(ITypeLib *This, TLIBATTR **ppTLibAttr);
  HRESULT (__stdcall *GetTypeComp)(ITypeLib *This, ITypeComp **ppTComp);
  HRESULT (__stdcall *GetDocumentation)(ITypeLib *This, INT index, BSTR *pBstrName, BSTR *pBstrDocString, DWORD *pdwHelpContext, BSTR *pBstrHelpFile);
  HRESULT (__stdcall *IsName)(ITypeLib *This, LPOLESTR szNameBuf, ULONG lHashVal, BOOL *pfName);
  HRESULT (__stdcall *FindName)(ITypeLib *This, LPOLESTR szNameBuf, ULONG lHashVal, ITypeInfo **ppTInfo, MEMBERID *rgMemId, USHORT *pcFound);
  void (__stdcall *ReleaseTLibAttr)(ITypeLib *This, TLIBATTR *pTLibAttr);
};
#pragma pack(pop)

/* 68 */
#pragma pack(push, 8)
union tagBINDPTR
{
  FUNCDESC *lpfuncdesc;
  VARDESC *lpvardesc;
  ITypeComp *lptcomp;
};
#pragma pack(pop)

/* 133 */
enum tagSYSKIND
{
  SYS_WIN16 = 0x0,
  SYS_WIN32 = 0x1,
  SYS_MAC = 0x2,
  SYS_WIN64 = 0x3,
};

/* 132 */
typedef enum tagSYSKIND SYSKIND;

/* 131 */
#pragma pack(push, 8)
struct tagTLIBATTR
{
  GUID guid;
  LCID lcid;
  SYSKIND syskind;
  WORD wMajorVerNum;
  WORD wMinorVerNum;
  WORD wLibFlags;
};
#pragma pack(pop)

/* 134 */
typedef unsigned __int16 wint_t;

/* 136 */
typedef const struct _s_ThrowInfo ThrowInfo;

/* 135 */
typedef ThrowInfo _ThrowInfo;

/* 138 */
typedef void (__cdecl *PMFN)(void *);

/* 139 */
typedef const struct _s_CatchableTypeArray CatchableTypeArray;

/* 137 */
#pragma pack(push, 4)
struct _s_ThrowInfo
{
  unsigned int attributes;
  PMFN pmfnUnwind;
  int (__cdecl *pForwardCompat)();
  CatchableTypeArray *pCatchableTypeArray;
};
#pragma pack(pop)

/* 141 */
typedef const struct _s_CatchableType CatchableType;

/* 140 */
#pragma pack(push, 4)
struct _s_CatchableTypeArray
{
  int nCatchableTypes;
  CatchableType *arrayOfCatchableTypes[];
};
#pragma pack(pop)

/* 143 */
#pragma pack(push, 4)
struct PMD
{
  int mdisp;
  int pdisp;
  int vdisp;
};
#pragma pack(pop)

/* 142 */
#pragma pack(push, 4)
struct _s_CatchableType
{
  unsigned int properties;
  TypeDescriptor *pType;
  PMD thisDisplacement;
  int sizeOrOffset;
  PMFN copyFunction;
};
#pragma pack(pop)

/* 144 */
#pragma pack(push, 8)
struct tm
{
  int tm_sec;
  int tm_min;
  int tm_hour;
  int tm_mday;
  int tm_mon;
  int tm_year;
  int tm_wday;
  int tm_yday;
  int tm_isdst;
};
#pragma pack(pop)

/* 146 */
typedef unsigned int _dev_t;

/* 147 */
typedef unsigned __int16 _ino_t;

/* 148 */
typedef int _off_t;

/* 145 */
#pragma pack(push, 8)
struct _stat64i32
{
  _dev_t st_dev;
  _ino_t st_ino;
  unsigned __int16 st_mode;
  __int16 st_nlink;
  __int16 st_uid;
  __int16 st_gid;
  _dev_t st_rdev;
  _off_t st_size;
  __time64_t st_atime;
  __time64_t st_mtime;
  __time64_t st_ctime;
};
#pragma pack(pop)

/* 149 */
typedef struct HDC__ *HDC;

/* 150 */
struct HDC__
{
  int unused;
};

/* 151 */
typedef struct HWND__ *HWND;

/* 152 */
struct HWND__
{
  int unused;
};

/* 153 */
typedef void *HGDIOBJ;

/* 156 */
struct tagRECT
{
  LONG left;
  LONG top;
  LONG right;
  LONG bottom;
};

/* 155 */
typedef struct tagRECT RECT;

/* 154 */
struct tagPAINTSTRUCT
{
  HDC hdc;
  BOOL fErase;
  RECT rcPaint;
  BOOL fRestore;
  BOOL fIncUpdate;
  BYTE rgbReserved[32];
};

/* 158 */
typedef unsigned int UINT_PTR;

/* 157 */
typedef UINT_PTR WPARAM;

/* 160 */
typedef int LONG_PTR;

/* 159 */
typedef LONG_PTR LPARAM;

/* 161 */
typedef struct tagWNDCLASSEXA WNDCLASSEXA;

/* 164 */
typedef LONG_PTR LRESULT;

/* 163 */
typedef LRESULT (__stdcall *WNDPROC)(HWND, UINT, WPARAM, LPARAM);

/* 165 */
typedef struct HICON__ *HICON;

/* 167 */
typedef HICON HCURSOR;

/* 168 */
typedef struct HBRUSH__ *HBRUSH;

/* 162 */
struct tagWNDCLASSEXA
{
  UINT cbSize;
  UINT style;
  WNDPROC lpfnWndProc;
  int cbClsExtra;
  int cbWndExtra;
  HINSTANCE hInstance;
  HICON hIcon;
  HCURSOR hCursor;
  HBRUSH hbrBackground;
  LPCSTR lpszMenuName;
  LPCSTR lpszClassName;
  HICON hIconSm;
};

/* 166 */
struct HICON__
{
  int unused;
};

/* 169 */
struct HBRUSH__
{
  int unused;
};

/* 170 */
typedef unsigned __int64 DWORD64;

/* 171 */
#pragma pack(push, 8)
struct _IMAGEHLP_SYMBOL64
{
  DWORD SizeOfStruct;
  DWORD64 Address;
  DWORD Size;
  DWORD Flags;
  DWORD MaxNameLength;
  CHAR Name[1];
};
#pragma pack(pop)

/* 173 */
typedef CHAR *PCHAR;

/* 172 */
#pragma pack(push, 8)
struct _IMAGEHLP_LINE64
{
  DWORD SizeOfStruct;
  PVOID Key;
  DWORD LineNumber;
  PCHAR FileName;
  DWORD64 Address;
};
#pragma pack(pop)

/* 174 */
typedef struct _CONTEXT CONTEXT;

/* 177 */
struct _FLOATING_SAVE_AREA
{
  DWORD ControlWord;
  DWORD StatusWord;
  DWORD TagWord;
  DWORD ErrorOffset;
  DWORD ErrorSelector;
  DWORD DataOffset;
  DWORD DataSelector;
  BYTE RegisterArea[80];
  DWORD Spare0;
};

/* 176 */
typedef struct _FLOATING_SAVE_AREA FLOATING_SAVE_AREA;

/* 175 */
#pragma pack(push, 4)
struct _CONTEXT
{
  DWORD ContextFlags;
  DWORD Dr0;
  DWORD Dr1;
  DWORD Dr2;
  DWORD Dr3;
  DWORD Dr6;
  DWORD Dr7;
  FLOATING_SAVE_AREA FloatSave;
  DWORD SegGs;
  DWORD SegFs;
  DWORD SegEs;
  DWORD SegDs;
  DWORD Edi;
  DWORD Esi;
  DWORD Ebx;
  DWORD Edx;
  DWORD Ecx;
  DWORD Eax;
  DWORD Ebp;
  DWORD Eip;
  DWORD SegCs;
  DWORD EFlags;
  DWORD Esp;
  DWORD SegSs;
  BYTE ExtendedRegisters[512];
};
#pragma pack(pop)

/* 181 */
typedef enum $8C57D1DDA788D6050A7C554DBD1EB1AC ADDRESS_MODE;

/* 180 */
#pragma pack(push, 8)
struct _tagADDRESS64
{
  DWORD64 Offset;
  WORD Segment;
  ADDRESS_MODE Mode;
};
#pragma pack(pop)

/* 179 */
typedef struct _tagADDRESS64 ADDRESS64;

/* 184 */
#pragma pack(push, 8)
struct _KDHELP64
{
  DWORD64 Thread;
  DWORD ThCallbackStack;
  DWORD ThCallbackBStore;
  DWORD NextCallback;
  DWORD FramePointer;
  DWORD64 KiCallUserMode;
  DWORD64 KeUserCallbackDispatcher;
  DWORD64 SystemRangeStart;
  DWORD64 KiUserExceptionDispatcher;
  DWORD64 StackBase;
  DWORD64 StackLimit;
  DWORD BuildVersion;
  DWORD RetpolineStubFunctionTableSize;
  DWORD64 RetpolineStubFunctionTable;
  DWORD RetpolineStubOffset;
  DWORD RetpolineStubSize;
  DWORD64 Reserved0[2];
};
#pragma pack(pop)

/* 183 */
typedef struct _KDHELP64 KDHELP64;

/* 178 */
#pragma pack(push, 8)
struct _tagSTACKFRAME64
{
  ADDRESS64 AddrPC;
  ADDRESS64 AddrReturn;
  ADDRESS64 AddrFrame;
  ADDRESS64 AddrStack;
  ADDRESS64 AddrBStore;
  PVOID FuncTableEntry;
  DWORD64 Params[4];
  BOOL Far;
  BOOL Virtual;
  DWORD64 Reserved[3];
  KDHELP64 KdHelp;
};
#pragma pack(pop)

/* 185 */
typedef union _LARGE_INTEGER LARGE_INTEGER;

/* 186 */
union _LARGE_INTEGER
{
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  };
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  } u;
  LONGLONG QuadPart;
};

/* 188 */
typedef struct HKEY__ *HKEY;

/* 189 */
struct HKEY__
{
  int unused;
};

/* 193 */
typedef void *LPVOID;

/* 194 */
typedef ULONG_PTR DWORD_PTR;

/* 190 */
struct _SYSTEM_INFO
{
  union
  {
    DWORD dwOemId;
    struct
    {
      WORD wProcessorArchitecture;
      WORD wReserved;
    };
  };
  DWORD dwPageSize;
  LPVOID lpMinimumApplicationAddress;
  LPVOID lpMaximumApplicationAddress;
  DWORD_PTR dwActiveProcessorMask;
  DWORD dwNumberOfProcessors;
  DWORD dwProcessorType;
  DWORD dwAllocationGranularity;
  WORD wProcessorLevel;
  WORD wProcessorRevision;
};

/* 195 */
typedef const WCHAR *LPCWSTR;

/* 196 */
typedef HINSTANCE HMODULE;

/* 197 */
typedef struct _SHELLEXECUTEINFOA SHELLEXECUTEINFOA;

/* 198 */
#pragma pack(push, 1)
struct _SHELLEXECUTEINFOA
{
  DWORD cbSize;
  ULONG fMask;
  HWND hwnd;
  LPCSTR lpVerb;
  LPCSTR lpFile;
  LPCSTR lpParameters;
  LPCSTR lpDirectory;
  int nShow;
  HINSTANCE hInstApp;
  void *lpIDList;
  LPCSTR lpClass;
  HKEY hkeyClass;
  DWORD dwHotKey;
  #pragma pack(push, 1)
  union
  {
    HANDLE hIcon;
    HANDLE hMonitor;
  };
  #pragma pack(pop)
  HANDLE hProcess;
};
#pragma pack(pop)

/* 202 */
struct tagPOINT
{
  LONG x;
  LONG y;
};

/* 201 */
typedef struct tagPOINT POINT;

/* 200 */
struct tagMSG
{
  HWND hwnd;
  UINT message;
  WPARAM wParam;
  LPARAM lParam;
  DWORD time;
  POINT pt;
};

/* 204 */
typedef CHAR *LPSTR;

/* 205 */
typedef BYTE *LPBYTE;

/* 203 */
struct _STARTUPINFOA
{
  DWORD cb;
  LPSTR lpReserved;
  LPSTR lpDesktop;
  LPSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};

/* 206 */
struct _PROCESS_INFORMATION
{
  HANDLE hProcess;
  HANDLE hThread;
  DWORD dwProcessId;
  DWORD dwThreadId;
};

/* 207 */
struct _OSVERSIONINFOA
{
  DWORD dwOSVersionInfoSize;
  DWORD dwMajorVersion;
  DWORD dwMinorVersion;
  DWORD dwBuildNumber;
  DWORD dwPlatformId;
  CHAR szCSDVersion[128];
};

/* 209 */
typedef unsigned int _fsize_t;

/* 208 */
#pragma pack(push, 8)
struct _finddata64i32_t
{
  unsigned int attrib;
  __time64_t time_create;
  __time64_t time_access;
  __time64_t time_write;
  _fsize_t size;
  char name[260];
};
#pragma pack(pop)

/* 210 */
typedef UINT_PTR SOCKET;

/* 212 */
typedef USHORT ADDRESS_FAMILY;

/* 211 */
struct sockaddr
{
  ADDRESS_FAMILY sa_family;
  CHAR sa_data[14];
};

/* 213 */
typedef unsigned __int16 u_short;

/* 214 */
typedef unsigned int u_long;

/* 216 */
typedef unsigned int u_int;

/* 215 */
struct fd_set
{
  u_int fd_count;
  SOCKET fd_array[64];
};

/* 217 */
struct timeval
{
  int tv_sec;
  int tv_usec;
};

/* 218 */
struct WSAData
{
  WORD wVersion;
  WORD wHighVersion;
  char szDescription[257];
  char szSystemStatus[129];
  unsigned __int16 iMaxSockets;
  unsigned __int16 iMaxUdpDg;
  char *lpVendorInfo;
};

/* 220 */
typedef struct _IP_ADDR_STRING *PIP_ADDR_STRING;

/* 222 */
typedef struct $F03B70C123AB6920C4DDA521DD856E56 IP_ADDRESS_STRING;

/* 224 */
typedef struct $F03B70C123AB6920C4DDA521DD856E56 IP_MASK_STRING;

/* 221 */
struct _IP_ADDR_STRING
{
  struct _IP_ADDR_STRING *Next;
  IP_ADDRESS_STRING IpAddress;
  IP_MASK_STRING IpMask;
  DWORD Context;
};

/* 225 */
typedef struct _IP_ADDR_STRING IP_ADDR_STRING;

/* 226 */
typedef int __time32_t;

/* 219 */
struct _IP_ADAPTER_INFO
{
  struct _IP_ADAPTER_INFO *Next;
  DWORD ComboIndex;
  char AdapterName[260];
  char Description[132];
  UINT AddressLength;
  BYTE Address[8];
  DWORD Index;
  UINT Type;
  UINT DhcpEnabled;
  PIP_ADDR_STRING CurrentIpAddress;
  IP_ADDR_STRING IpAddressList;
  IP_ADDR_STRING GatewayList;
  IP_ADDR_STRING DhcpServer;
  BOOL HaveWins;
  IP_ADDR_STRING PrimaryWinsServer;
  IP_ADDR_STRING SecondaryWinsServer;
  __time32_t LeaseObtained;
  __time32_t LeaseExpires;
};

/* 229 */
typedef LONG PDH_STATUS;

/* 228 */
typedef PDH_STATUS (__stdcall *CounterPathCallBack)(DWORD_PTR);

/* 227 */
struct _BrowseDlgConfig_A
{
  unsigned __int32 bIncludeInstanceIndex : 1;
  unsigned __int32 bSingleCounterPerAdd : 1;
  unsigned __int32 bSingleCounterPerDialog : 1;
  unsigned __int32 bLocalCountersOnly : 1;
  unsigned __int32 bWildCardInstances : 1;
  unsigned __int32 bHideDetailBox : 1;
  unsigned __int32 bInitializePath : 1;
  unsigned __int32 bDisableMachineSelection : 1;
  unsigned __int32 bIncludeCostlyObjects : 1;
  unsigned __int32 bShowObjectBrowser : 1;
  unsigned __int32 bReserved : 22;
  HWND hWndOwner;
  LPSTR szDataSource;
  LPSTR szReturnPathBuffer;
  DWORD cchReturnPathLength;
  CounterPathCallBack pCallBack;
  DWORD_PTR dwCallBackArg;
  PDH_STATUS CallBackStatus;
  DWORD dwDefaultDetailLevel;
  LPSTR szDialogBoxCaption;
};

/* 231 */
typedef ULONGLONG DWORDLONG;

/* 230 */
struct _MEMORYSTATUSEX
{
  DWORD dwLength;
  DWORD dwMemoryLoad;
  DWORDLONG ullTotalPhys;
  DWORDLONG ullAvailPhys;
  DWORDLONG ullTotalPageFile;
  DWORDLONG ullAvailPageFile;
  DWORDLONG ullTotalVirtual;
  DWORDLONG ullAvailVirtual;
  DWORDLONG ullAvailExtendedVirtual;
};

/* 232 */
typedef ULONG_PTR SIZE_T;

/* 233 */
typedef char *va_list;

/* 234 */
struct _DISPLAY_DEVICEA
{
  DWORD cb;
  CHAR DeviceName[32];
  CHAR DeviceString[128];
  DWORD StateFlags;
  CHAR DeviceID[128];
  CHAR DeviceKey[128];
};

/* 235 */
typedef const GUID *LPCGUID;

/* 236 */
typedef GUID *LPGUID;

/* 237 */
typedef struct tagWNDCLASSA WNDCLASSA;

/* 238 */
struct tagWNDCLASSA
{
  UINT style;
  WNDPROC lpfnWndProc;
  int cbClsExtra;
  int cbWndExtra;
  HINSTANCE hInstance;
  HICON hIcon;
  HCURSOR hCursor;
  HBRUSH hbrBackground;
  LPCSTR lpszMenuName;
  LPCSTR lpszClassName;
};

/* 239 */
typedef struct tagPIXELFORMATDESCRIPTOR PIXELFORMATDESCRIPTOR;

/* 240 */
struct tagPIXELFORMATDESCRIPTOR
{
  WORD nSize;
  WORD nVersion;
  DWORD dwFlags;
  BYTE iPixelType;
  BYTE cColorBits;
  BYTE cRedBits;
  BYTE cRedShift;
  BYTE cGreenBits;
  BYTE cGreenShift;
  BYTE cBlueBits;
  BYTE cBlueShift;
  BYTE cAlphaBits;
  BYTE cAlphaShift;
  BYTE cAccumBits;
  BYTE cAccumRedBits;
  BYTE cAccumGreenBits;
  BYTE cAccumBlueBits;
  BYTE cAccumAlphaBits;
  BYTE cDepthBits;
  BYTE cStencilBits;
  BYTE cAuxBuffers;
  BYTE iLayerType;
  BYTE bReserved;
  DWORD dwLayerMask;
  DWORD dwVisibleMask;
  DWORD dwDamageMask;
};

/* 241 */
typedef struct _devicemodeA DEVMODEA;

/* 247 */
struct _POINTL
{
  LONG x;
  LONG y;
};

/* 246 */
typedef struct _POINTL POINTL;

/* 242 */
struct _devicemodeA
{
  BYTE dmDeviceName[32];
  WORD dmSpecVersion;
  WORD dmDriverVersion;
  WORD dmSize;
  WORD dmDriverExtra;
  DWORD dmFields;
  union
  {
    struct
    {
      __int16 dmOrientation;
      __int16 dmPaperSize;
      __int16 dmPaperLength;
      __int16 dmPaperWidth;
      __int16 dmScale;
      __int16 dmCopies;
      __int16 dmDefaultSource;
      __int16 dmPrintQuality;
    };
    struct
    {
      POINTL dmPosition;
      DWORD dmDisplayOrientation;
      DWORD dmDisplayFixedOutput;
    };
  };
  __int16 dmColor;
  __int16 dmDuplex;
  __int16 dmYResolution;
  __int16 dmTTOption;
  __int16 dmCollate;
  BYTE dmFormName[32];
  WORD dmLogPixels;
  DWORD dmBitsPerPel;
  DWORD dmPelsWidth;
  DWORD dmPelsHeight;
  union
  {
    DWORD dmDisplayFlags;
    DWORD dmNup;
  };
  DWORD dmDisplayFrequency;
  DWORD dmICMMethod;
  DWORD dmICMIntent;
  DWORD dmMediaType;
  DWORD dmDitherType;
  DWORD dmReserved1;
  DWORD dmReserved2;
  DWORD dmPanningWidth;
  DWORD dmPanningHeight;
};

/* 249 */
typedef struct HMONITOR__ *HMONITOR;

/* 250 */
struct HMONITOR__
{
  int unused;
};

/* 251 */
struct tagMONITORINFO
{
  DWORD cbSize;
  RECT rcMonitor;
  RECT rcWork;
  DWORD dwFlags;
};

/* 252 */
typedef struct tagRECT *LPRECT;

/* 253 */
typedef struct HIMC__ *HIMC;

/* 254 */
struct HIMC__
{
  int unused;
};

/* 255 */
typedef double GLdouble;

/* 256 */
typedef HANDLE PDH_HQUERY;

/* 257 */
typedef struct _BrowseDlgConfig_A *PPDH_BROWSE_DLG_CONFIG_A;

/* 258 */
typedef HANDLE PDH_HCOUNTER;

/* 259 */
typedef DWORD *LPDWORD;

/* 260 */
typedef struct _PDH_FMT_COUNTERVALUE *PPDH_FMT_COUNTERVALUE;

/* 261 */
struct _PDH_FMT_COUNTERVALUE
{
  DWORD CStatus;
  union
  {
    LONG longValue;
    double doubleValue;
    LONGLONG largeValue;
    LPCSTR AnsiStringValue;
    LPCWSTR WideStringValue;
  };
};

/* 263 */
typedef struct _IP_ADAPTER_INFO *PIP_ADAPTER_INFO;

/* 264 */
typedef ULONG *PULONG;

/* 265 */
typedef struct tagCANDIDATELIST *LPCANDIDATELIST;

/* 266 */
struct tagCANDIDATELIST
{
  DWORD dwSize;
  DWORD dwStyle;
  DWORD dwCount;
  DWORD dwSelection;
  DWORD dwPageStart;
  DWORD dwPageSize;
  DWORD dwOffset[1];
};

/* 267 */
typedef struct HKL__ *HKL;

/* 268 */
struct HKL__
{
  int unused;
};

/* 269 */
typedef const void *LPCVOID;

/* 270 */
typedef unsigned int *PUINT;

/* 272 */
typedef struct _RTL_CRITICAL_SECTION *PRTL_CRITICAL_SECTION;

/* 271 */
typedef PRTL_CRITICAL_SECTION LPCRITICAL_SECTION;

/* 274 */
typedef struct _RTL_CRITICAL_SECTION_DEBUG *PRTL_CRITICAL_SECTION_DEBUG;

/* 273 */
#pragma pack(push, 8)
struct _RTL_CRITICAL_SECTION
{
  PRTL_CRITICAL_SECTION_DEBUG DebugInfo;
  LONG LockCount;
  LONG RecursionCount;
  HANDLE OwningThread;
  HANDLE LockSemaphore;
  ULONG_PTR SpinCount;
};
#pragma pack(pop)

/* 277 */
struct _LIST_ENTRY
{
  struct _LIST_ENTRY *Flink;
  struct _LIST_ENTRY *Blink;
};

/* 276 */
typedef struct _LIST_ENTRY LIST_ENTRY;

/* 275 */
struct _RTL_CRITICAL_SECTION_DEBUG
{
  WORD Type;
  WORD CreatorBackTraceIndex;
  struct _RTL_CRITICAL_SECTION *CriticalSection;
  LIST_ENTRY ProcessLocksList;
  DWORD EntryCount;
  DWORD ContentionCount;
  DWORD Flags;
  WORD CreatorBackTraceIndexHigh;
  WORD SpareWORD;
};

/* 278 */
typedef unsigned int (__stdcall *_beginthreadex_proc_type)(void *);

/* 279 */
typedef IUnknown *LPUNKNOWN;

/* 280 */
typedef BOOL (__stdcall *LPDSENUMCALLBACKW)(LPGUID, LPCWSTR, LPCWSTR, LPVOID);

/* 281 */
typedef int (__cdecl *_CoreCrtNonSecureSearchSortCompareFunction)(const void *, const void *);

/* 282 */
typedef int (__cdecl *_onexit_t)();

/* 283 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 286 */
typedef struct _EXCEPTION_RECORD EXCEPTION_RECORD;

/* 285 */
typedef EXCEPTION_RECORD *PEXCEPTION_RECORD;

/* 288 */
typedef CONTEXT *PCONTEXT;

/* 284 */
struct _EXCEPTION_POINTERS
{
  PEXCEPTION_RECORD ExceptionRecord;
  PCONTEXT ContextRecord;
};

/* 287 */
struct _EXCEPTION_RECORD
{
  DWORD ExceptionCode;
  DWORD ExceptionFlags;
  struct _EXCEPTION_RECORD *ExceptionRecord;
  PVOID ExceptionAddress;
  DWORD NumberParameters;
  ULONG_PTR ExceptionInformation[15];
};

/* 289 */
typedef unsigned int uintptr_t;

/* 290 */
struct sdDeviceContextLocal;

/* 291 */
struct idCmdArgs;

/* 292 */
struct idAudioSample;

/* 293 */
struct imageParams_t;

/* 294 */
struct idCVarCallback_SkipSpecular;

/* 295 */
struct idCVarCallback_SkipBump;

/* 296 */
struct idCVarCallback_SkipDiffuse;

/* 297 */
struct rvParticle;

/* 298 */
struct sdOcclusionQueryWrapper;

/* 299 */
struct sdOcclusionQuery;

/* 300 */
struct sdOcclusionTestLocal;

/* 301 */
struct fileInPack_s;

/* 302 */
struct idSampleDecoder;

/* 303 */
struct idSoundEmitter;

/* 304 */
struct idRenderModelStatic;

/* 305 */
struct sdFontManagerLocal;

/* 306 */
struct idSoundEmitterLocal;

/* 307 */
struct idToken;

/* 308 */
struct sdFrameBuffer;

/* 309 */
struct sdFrameBufferManager;

/* 310 */
struct renderBuffer_t;

/* 311 */
struct sdGuiModel;

/* 312 */
struct idImage;

/* 313 */
struct idImageManager;

/* 314 */
struct idFixedWinding;

/* 315 */
struct backgroundDownload_t;

/* 316 */
struct sdConvolve2D;

/* 317 */
struct sdFilterFilter;

/* 318 */
struct sdTriangleFilter;

/* 319 */
struct sdBellFilter;

/* 320 */
struct sdBSplineFilter;

/* 321 */
struct sdMitchellFilter;

/* 322 */
struct sdBoxFilter;

/* 323 */
struct sdImageSequence;

/* 324 */
struct sdImposterSubImage;

/* 325 */
struct idMaterial;

/* 326 */
struct idInteraction;

/* 327 */
struct idDecl;

/* 328 */
struct stageParseData_t;

/* 329 */
struct idSoundShader;

/* 330 */
struct sdDeclTypeHolder;

/* 331 */
struct sdDeclParseHelper;

/* 332 */
struct idFile_Memory;

/* 333 */
struct idSoundSystem;

/* 334 */
struct idSoundSystemLocal;

/* 335 */
struct idSoundWorld;

/* 336 */
struct idSoundWorldLocal;

/* 337 */
struct rvRenderModelBSE;

/* 338 */
struct idCmdSystem;

/* 339 */
struct idRenderSystemLocal;

/* 340 */
struct idRenderModelLiquid;

/* 341 */
struct idRenderModelMD3;

/* 342 */
struct idMD5Mesh;

/* 343 */
struct idRenderModelMD5;

/* 344 */
struct idCommonLocal;

/* 345 */
struct sdStuffCache;

/* 346 */
struct sdStuffQuadTree;

/* 347 */
struct idCommon;

/* 348 */
struct idWStr;

/* 349 */
struct sdRenderModelDecal;

/* 350 */
struct idRenderModelDecal;

/* 351 */
struct idRenderModelManagerLocal;

/* 352 */
struct sdRenderBindingManager;

/* 353 */
struct rvRenderEffectLocal;

/* 354 */
struct idCVar;

/* 355 */
struct idRenderLog;

/* 356 */
struct idCompressor_Huffman;

/* 357 */
struct idCompressor_None;

/* 358 */
struct idConsole;

/* 359 */
struct smpCommandQueue;

/* 360 */
struct smpCommandQueueBuffer;

/* 361 */
struct idCVarSystemLocal;

/* 362 */
struct idCVarSystem;

/* 363 */
struct idDeclBase;

/* 364 */
struct idDeclManager;

/* 365 */
struct idDeclManagerLocal;

/* 366 */
struct idDeclLocal;

/* 367 */
struct idRenderWorldLocal;

/* 368 */
struct sdRenderSystemBackend;

/* 369 */
struct renderLight_t;

/* 370 */
struct renderEffect_s;

/* 371 */
struct idScreenRect;

/* 372 */
struct vcache;

/* 373 */
struct sdPerformanceQueryLocal;

/* 374 */
struct debugPolygon_s;

/* 375 */
struct polyhedron;

/* 376 */
struct poly;

/* 377 */
struct idVertexCache;

/* 378 */
struct idMegaTexture;

/* 379 */
struct idMegaTextureLevel;

/* 380 */
struct idMegaTextureTile;

/* 381 */
struct tileData_t;

/* 382 */
struct idMegaTextureTileDecompressor;

/* 383 */
struct sdAudioDevice_Software;

/* 384 */
struct sdAudioHardware_Software;

/* 385 */
struct idStreamingAudioSample;

/* 386 */
struct sdBinkFile;

/* 387 */
struct idSampleDecoderLocal;

/* 388 */
struct idSoundCache;

/* 389 */
struct idSoundFade;

/* 390 */
struct idSoundChannel;

/* 391 */
struct idSoundSample;

/* 392 */
struct idAudioHardware;

/* 393 */
struct sdNetSessionManager_Local;

/* 394 */
struct rvDecalParticle;

/* 395 */
struct sdTheoraFile;

/* 396 */
struct idWaveFile;

/* 397 */
struct idCmdSystemLocal;

/* 398 */
struct idFileSystemLocal;

/* 399 */
struct idCompressor_FixedHuffman;

/* 400 */
struct idConsoleLocal;

/* 401 */
struct idInternalCVar;

/* 402 */
struct sdDeclRenderProgram;

/* 403 */
struct sdDeclRenderBinding;

/* 404 */
struct idDeclType;

/* 405 */
struct idFile_Permanent;

/* 406 */
struct sdDeclSurfaceType;

/* 407 */
struct sdDeclSurfaceTypeMap;

/* 408 */
struct idFileSystem;

/* 409 */
struct sdGraphManager;

/* 410 */
struct sdNotificationSystemLocal;

/* 411 */
struct idSessionLocal;

/* 412 */
struct idSession;

/* 413 */
struct idUsercmdGenLocal;

/* 414 */
struct idAsyncServer;

/* 415 */
struct sdAsyncVoice;

/* 416 */
struct idNetworkSystem;

/* 417 */
struct sdAdManager;

/* 418 */
struct idEditField;

/* 419 */
struct idEventLoop;

/* 420 */
struct idFile_InZip;

/* 421 */
struct sdAdObjectSubscriber;

/* 422 */
struct sdKeyInputManagerLocal;

/* 423 */
struct metaDataContext_t;

/* 424 */
struct sdAddonInfo;

/* 425 */
struct idDEntry;

/* 426 */
struct sdControllerAPI;

/* 427 */
struct sdControllerAPIDInput;

/* 428 */
struct sdGraphManagerLocal;

/* 429 */
struct sdBindContext;

/* 430 */
struct sdKeyBind;

/* 431 */
struct idKey;

/* 432 */
struct sdControllerAPIXInput;

/* 433 */
struct idSys;

/* 434 */
struct idMsgQueue;

/* 435 */
struct idAsyncClient;

/* 436 */
struct binaryDeclEntry_t;

/* 437 */
struct idUpdateCheck;

/* 438 */
struct idAudioCaptureBuffer;

/* 439 */
struct idAudioHardwareDSound::sdSoundDevice;

/* 440 */
struct idAudioHardwareDSound;

/* 441 */
struct id3DContext;

/* 442 */
struct id3DContextWinGL;

/* 443 */
struct idServerClientBase;

/* 444 */
struct idAsyncServerBase;

/* 445 */
struct sdDemo;

/* 446 */
struct idMsgChannel;

/* 447 */
struct idBitMsgQueue;

/* 448 */
struct idCollisionModelLocal;

/* 449 */
struct idAudioChannel;

/* 450 */
struct sdController;

/* 451 */
struct sdControllerManager;

/* 452 */
struct sdControllerManagerLocal;

/* 453 */
struct idSysLocal;

/* 454 */
struct sdSplashScreen;

/* 455 */
struct idAudioHardwareOpenAL;

/* 456 */
struct sdLogitechLCDSystemLocal;

/* 457 */
struct idFile;

/* 458 */
struct idPort;

/* 459 */
struct idAudioCaptureBufferDSound;

/* 460 */
struct idAudioBufferDSound;

/* 461 */
struct sdDInputController;

/* 462 */
struct sdIMEWin;

/* 463 */
struct idRenderContextWGL;

/* 464 */
struct idAudioCaptureBufferOpenAL;

/* 465 */
struct idAudioChannelOpenAL;

/* 466 */
struct idAudioHardwareOpenAL::audioSource_t;

/* 467 */
struct idOpenALAudioSample;

/* 468 */
struct idMouse;

/* 469 */
struct sdIMEWin::sdUIElementSink;

/* 470 */
struct bdMessage;

/* 471 */
struct idMouseRawInput;

/* 472 */
struct idCollisionModel;

/* 473 */
struct idCollisionModelManager;

/* 474 */
struct sdNetAccount_Local;

/* 475 */
struct idKeyboardWin32;

/* 476 */
struct idMouseDInput;

/* 477 */
struct sdNetTask_Local;

/* 478 */
struct sdXInputController;

/* 479 */
struct bdLobbyFileHeader;

/* 480 */
struct sdNetService;

/* 481 */
struct sdNetUser;

/* 482 */
struct sdNetAccount_DemonWare;

/* 483 */
struct idCollisionModelManagerLocal;

/* 484 */
struct idModelCache;

/* 485 */
struct sdNetProfile;

/* 486 */
struct sdNetService_Local;

/* 487 */
struct sdNetSession;

/* 488 */
struct sdNetSession_Local;

/* 489 */
struct sdNetProfile_Local;

/* 490 */
struct bdNetImpl;

/* 491 */
struct imageClassUsage_t;

/* 492 */
struct bdMessageStore;

/* 493 */
struct sdLogSubscriber;

/* 494 */
struct sdNetUser_Local;

/* 495 */
struct sdNetSession_DemonWare;

/* 496 */
struct sdNetService::motdEntry_t;

/* 497 */
struct sdNetTask_DemonWare_SignIn;

/* 498 */
struct sdNetUser_DemonWare;

/* 499 */
struct sdNetService_DemonWare;

/* 500 */
struct idDeclSkin;

/* 501 */
struct rvBSEManagerLocal;

/* 502 */
struct rvBSE;

/* 503 */
struct bdSessionInfo;

/* 504 */
struct idDxtEncoder;

/* 505 */
struct idDxtDecoder;

/* 506 */
struct idBareDctDecoder;

/* 507 */
struct idBareDctBase;

/* 508 */
struct idBareDCTHuffmanTable;

/* 509 */
struct sdNetSessionManager_DemonWare;

/* 510 */
struct idAASSettings;

/* 511 */
struct idAASFileLocal;

/* 512 */
struct idStr;

/* 513 */
struct idWinding2D;

/* 514 */
struct sdDeclAmbientCubeMap;

/* 515 */
struct idHeap;

/* 516 */
struct idTimer;

/* 517 */
struct idBounds;

/* 518 */
struct idLexer;

/* 519 */
struct idParser;

/* 520 */
struct idVec2;

/* 521 */
struct idVec3;

/* 522 */
struct idFrustum;

/* 523 */
struct idBox;

/* 524 */
struct idDict;

/* 525 */
struct idMat4;

/* 526 */
struct idWinding;

/* 527 */
struct sdThread;

/* 528 */
struct sdPerlin;

/* 529 */
struct sdSpeexStream;

/* 530 */
struct idLangDict;

/* 531 */
struct idTokenCache;

/* 532 */
struct idLexerBinary;

/* 533 */
struct idBitMsg;

/* 534 */
struct idBoundsShort;

/* 535 */
struct idTraceModel;

/* 536 */
struct idRotation;

/* 537 */
struct idWToken;

/* 538 */
struct sdUTF8;

/* 539 */
struct idWLexer;

/* 540 */
struct idSIMD_Generic;

/* 541 */
struct idDeclAF;

/* 542 */
struct idSIMD_MMX;

/* 543 */
struct idSIMD_SSE;

/* 544 */
struct sdDeclAtmosphere;

/* 545 */
struct idSIMD_3DNow;

/* 546 */
struct sdDeclStuffType;

/* 547 */
struct idSIMD_SSE2;

/* 548 */
struct idSIMD_SSE3;

/* 549 */
struct idFile_BitMsg;

/* 550 */
struct rvSpriteParticle;

/* 551 */
struct sdDeclDecal;

/* 552 */
struct idFile_Buffered;

/* 553 */
struct sdDeclAmbientCubeMap::ambientLight_t;

/* 554 */
struct sdDeclTemplate::Command;

/* 555 */
struct rvSegment;

/* 556 */
struct sdDeclTemplate;

/* 557 */
struct sdDeclSurfaceTypeMap::sdSurfaceTypeArea;

/* 558 */
struct sdDeclSurfaceTypeMap::sdSurfaceTypeAreaWinding;

/* 559 */
struct sdDeclImposter;

/* 560 */
struct sdDeclImposterGenerator;

/* 561 */
struct idAFVector;

/* 562 */
struct idDeclAF_Body;

/* 563 */
struct sdCloudLayer;

/* 564 */
struct sdDeclModelExport;

/* 565 */
struct idDeclTable;

/* 566 */
struct idDeclEntityDef;

/* 567 */
struct sdRenderShader;

/* 568 */
struct rvDeclEffect;

/* 569 */
struct rvLineParticle;

/* 570 */
struct sdRenderProgram;

/* 571 */
struct sdRenderProgramGLSL;

/* 572 */
struct sdRenderProgramARB;

/* 573 */
struct sdDeclLocStr;

/* 574 */
struct rvParticleTemplate;

/* 575 */
struct rvSegmentTemplate;

/* 576 */
struct rvDebrisParticle;

/* 577 */
struct rvLightParticle;

/* 578 */
struct rvOrientedParticle;

/* 579 */
struct rvModelParticle;

/* 580 */
struct rvElectricityParticle;

/* 581 */
struct rvLinkedParticle;

/* 582 */
struct sdOrientedLinkedParticle;

/* 583 */
struct sdRenderProgramParser;

/* 584 */
struct idRenderEntityLocal;

/* 585 */
struct sdRenderShaderARB;

/* 586 */
struct sdRenderShaderCg;

/* 587 */
struct sdRenderShaderGLSL;

/* 588 */
struct rvEnvParms;

/* 589 */
struct rvParticleParms;

/* 590 */
struct bdLogSubscriber;

/* 591 */
struct bdBitBuffer;

/* 592 */
struct bdLogImpl;

/* 593 */
struct bdMessageProxy;

/* 594 */
struct bdInetAddr;

/* 595 */
struct bdAddr;

/* 596 */
struct bdReferencable;

/* 597 */
struct bdByteBuffer;

/* 598 */
struct bdSecurityID;

/* 599 */
struct bdCommonAddr;

/* 600 */
struct bdString;

/* 601 */
struct bdCypher;

/* 602 */
struct bdHash;

/* 603 */
struct bdMutex;

/* 604 */
struct bdQueryResult;

/* 605 */
struct bdAuthTicket;

/* 606 */
struct bdRemoteTask;

/* 607 */
struct bdQoSReplyPacket;

/* 608 */
struct bdSecurityKeyMapListener;

/* 609 */
struct bdConnection;

/* 610 */
struct bdLobbyFile;

/* 611 */
struct bdMatchMaking;

/* 612 */
struct bdQoSProbe;

/* 613 */
struct std::locale::facet;

/* 614 */
struct bdStorage;

/* 615 */
struct bdAddrHandle;

/* 616 */
struct bdPacketInterceptor;

/* 617 */
struct bdDTLSError;

/* 618 */
struct bdGetMessagesResult;

/* 619 */
struct bdDTLSCookieAck;

/* 620 */
struct bdMatchMakingInfo;

/* 621 */
struct bdQueryParams;

/* 622 */
struct bdQoSRequestPacket;

/* 623 */
struct bdThread;

/* 624 */
struct bdTeams;

/* 625 */
struct bdLobbyConnection;

/* 626 */
struct bdUPnP;

/* 627 */
struct bdLobbyConnectionListener;

/* 628 */
struct bdLobbyMessage;

/* 629 */
struct bdChannelNotificationMessage;

/* 630 */
struct bdMMPlayerDisconnectMessage;

/* 631 */
struct bdUPnP::bdUPnPDevice;

/* 632 */
struct bdDispatcher;

/* 633 */
struct bdInAddr;

/* 634 */
struct bdQoSProbe::bdQoSProbeEntryWrapper;

/* 635 */
struct bdServiceBandwidthArbitrator;

/* 636 */
struct bdDTLSHeader;

/* 637 */
struct bdDTLSInit;

/* 638 */
struct bdDTLSInitAck;

/* 639 */
struct bdDTLSCookieEcho;

/* 640 */
struct type_info;

/* 641 */
struct bdLoopbackConnection;

/* 642 */
struct bdReliableSendWindow;

/* 643 */
struct bdUnreliableSendWindow;

/* 644 */
struct bdDataChunk;

/* 645 */
struct bdUnreliableReceiveWindow;

/* 646 */
struct bdConnectionStatistics;

/* 647 */
struct bdSAckChunk;

/* 648 */
struct bdCookie;

/* 649 */
struct bdPacket;

/* 650 */
struct bdChunk;

/* 651 */
struct bdStopwatch;

/* 652 */
struct bdSecurityKey;

/* 653 */
struct bdStreamSocket;

/* 654 */
struct bdSocket;

/* 655 */
struct bdShortTimer;

/* 656 */
struct bdHMac;

/* 657 */
struct idInitExclusions;

/* 658 */
struct idTCP;

/* 659 */
struct sdOcclusionQueryManager;

/* 660 */
struct sdLanczos3Filter;

/* 661 */
struct aseModel_s;

/* 662 */
struct objMesh_t;

/* 663 */
struct sdRenderModelStuff;

/* 664 */
struct sdStuffSurface;

/* 665 */
struct surfaceModel_t;

/* 666 */
struct idRenderModelOverlay;

/* 667 */
struct sdRenderSystemUtilities;

/* 668 */
struct renderEntity_t;

/* 669 */
struct sdSurfaceTypeMap;

/* 670 */
struct sdSurfaceTypeMapManager;

/* 671 */
struct sdPerformanceQueryEngine;

/* 672 */
struct sdOcclusionTest;

/* 673 */
struct idAudioChannelSoftware;

/* 674 */
struct idCVarCallback_SoundVolume;

/* 675 */
struct idRenderModel;

/* 676 */
struct sdRenderModelStuffInstance;

/* 677 */
struct sdWinKeysCallback;

/* 678 */
struct idRenderModelManager;

/* 679 */
struct rvRenderEffect;

/* 680 */
struct idRenderEntity;

/* 681 */
struct sdAsyncThread;

/* 682 */
struct idRenderSystem;

/* 683 */
struct idRenderWorld;

/* 684 */
struct sdPerformanceQuery;

/* 685 */
struct std::ios_base;

/* 686 */
struct idMegaTextureTileLoader;

/* 687 */
struct idDeclManagerLocal::declTypeData_t;

/* 688 */
struct sdDeclInfo;

/* 689 */
struct idDemoFile;

/* 690 */
struct sdGraph;

/* 691 */
struct sdGraph::category_t;

/* 692 */
struct idCVarCallback_RateChanged;

/* 693 */
struct usercmdDeltaInfo_t;

/* 694 */
struct sdSysEvent;

/* 695 */
typedef struct HBITMAP__ *HBITMAP;

/* 696 */
struct HBITMAP__
{
  int unused;
};

/* 697 */
struct tagBITMAP
{
  LONG bmType;
  LONG bmWidth;
  LONG bmHeight;
  LONG bmWidthBytes;
  WORD bmPlanes;
  WORD bmBitsPixel;
  LPVOID bmBits;
};

/* 698 */
struct sdPerformanceQueryWin;

/* 699 */
struct idAudioHardwareOpenAL::sdAlDevice;

/* 700 */
struct idUsercmdGen;

/* 701 */
struct filebuf;

/* 702 */
struct bdDTLSAssociation;

/* 703 */
struct sdTextUtilities;

/* 704 */
struct sdAdManagerLocal;

/* 705 */
struct idKeyboard;

/* 706 */
struct bdSingletonRegistryImpl;

/* 707 */
struct sdNetTask_DemonWare_SignOut;

/* 708 */
struct sdNetTask_DemonWare_SignOutDedicated;

/* 709 */
struct sdNetTask_DemonWare_NotifyLeave;

/* 710 */
struct sdNetTask_DemonWare_NotifyJoin;

/* 711 */
struct sdNetTask_DemonWare_UpdateSession;

/* 712 */
struct sdNetTask_DemonWare_CreateSession;

/* 713 */
struct idRenderLight;

/* 714 */
struct sdNetTask_DemonWare_DeleteSession;

/* 715 */
struct sdNetTask_DemonWare_RefreshSession;

/* 716 */
struct sdNetTask_DemonWare_RefreshSessions;

/* 717 */
struct sdLock;

/* 718 */
struct idJointMat;

/* 719 */
struct idStrPool;

/* 720 */
struct idQuat;

/* 721 */
struct sdSignal;

/* 722 */
struct idSphere;

/* 723 */
struct idAASFileManager;

/* 724 */
struct bdFriendshipProposalMessage;

/* 725 */
struct bdTeamSessionInvitationMessage;

/* 726 */
struct bdGetHostByName;

/* 727 */
struct bdSocketRouter;

/* 728 */
struct bdNATTypeDiscoveryClient;

/* 729 */
struct bdSecurityKeyMap;

/* 730 */
struct bdLogChannel;

/* 731 */
struct bdHMacSHA1;

/* 732 */
struct bdTrulyRandomImpl;

/* 733 */
struct bdHashTiger192;

/* 734 */
struct bdIPDiscoveryClient;

/* 735 */
struct bdLobbyServiceImpl;

/* 736 */
struct bdGetFileResult;

/* 737 */
struct bdNATTravListener;

/* 738 */
struct bdCustomQueryParams;

/* 739 */
struct bdSessionCreateResult;

/* 740 */
struct bdDTLSData;

/* 741 */
struct bdRemoteTaskManager;

/* 742 */
struct bdLobbyMessageFactoryImpl;

/* 743 */
struct bdUserNotificationMessage;

/* 744 */
struct bdFriendSessionInvitationMessage;

/* 745 */
struct bdTeamInvitationMessage;

/* 746 */
struct bdFriendCustomMessage;

/* 747 */
struct bdTeamNotificationMessage;

/* 748 */
struct bdTeamWideNotificationMessage;

/* 749 */
struct bdTeamCustomMessage;

/* 750 */
struct bdChannelChatMessage;

/* 751 */
struct bdProfileInfoUpdatedMessage;

/* 752 */
struct bdTeamInfoUpdatedMessage;

/* 753 */
struct bdNATTraversalPacket;

/* 754 */
struct bdNATTravClient::bdNATTravClientData;

/* 755 */
struct bdUnicastConnection;

/* 756 */
struct bdReliableReceiveWindow;

/* 757 */
struct bdReliableSendWindow::bdMessageFrame;

/* 758 */
struct bdInitChunk;

/* 759 */
struct bdInitAckChunk;

/* 760 */
struct bdCookieEchoChunk;

/* 761 */
struct bdCookieAckChunk;

/* 762 */
struct bdHeartbeatChunk;

/* 763 */
struct bdHeartbeatAckChunk;

/* 764 */
struct bdShutdownChunk;

/* 765 */
struct bdShutdownAckChunk;

/* 766 */
struct bdShutdownCompleteChunk;

/* 767 */
struct bdCypher3Des;

/* 768 */
struct idCVarCallback_MegaDrawMethod;

/* 769 */
struct idStrList;

/* 770 */
struct sdImageResampler;

/* 771 */
struct sdImposterGeometry;

/* 772 */
struct objParse_t;

/* 773 */
struct objModel_t;

/* 774 */
struct idCVarCallback_ShowCacheMegs;

/* 775 */
struct idSurface;

/* 776 */
struct idImageGeneratorFunctorGlobal;

/* 777 */
struct std::strstreambuf;

/* 778 */
struct sdMassiveThread;

/* 779 */
struct idModList;

/* 780 */
struct idServerClient;

/* 781 */
struct idUDPLag;

/* 782 */
struct winConData_t;

/* 783 */
struct idPoller;

/* 784 */
struct sdNetProfile_DemonWare;

/* 785 */
struct sdNetSessionManager;

/* 786 */
struct sdRenderModelCheapDecal;

/* 787 */
struct bdFindSessionsByPublicOpen;

/* 788 */
struct sdNetTask_DemonWare_FindSessionsLAN;

/* 789 */
struct bdFindRepeaterSessionsByPublicOpenResult;

/* 790 */
struct rvBSEManager;

/* 791 */
struct bdFindSessionsByPublicOpenResult;

/* 792 */
struct bdFindRankedSessionsByPublicOpen;

/* 793 */
struct bdFindRepeaterSessionsByPublicOpen;

/* 794 */
struct bdFindRankedSessionsByPublicOpenResult;

/* 795 */
struct idLangKeyValue;

/* 796 */
struct idDeclAF_Constraint;

/* 797 */
struct sdPrecipitationParameters;

/* 798 */
struct bdAuthService;

/* 799 */
struct sdDeclRenderProgram::parseData_t;

/* 800 */
struct std::locale::_Locimp;

/* 801 */
struct sdModelInfo;

/* 802 */
struct bdRunnable;

/* 803 */
struct bdAddressMapImpl;

/* 804 */
struct bdECCKey;

/* 805 */
struct urlDownload_s;

/* 806 */
struct soundDecoderInfo_t;

/* 807 */
struct sdImageProcessor;

/* 808 */
struct idRenderModelBeam;

/* 809 */
struct stuffCacheItem_t;

/* 810 */
struct idDeclFile;

/* 811 */
struct sdAddonMetaDataList;

/* 812 */
struct idFileList;

/* 813 */
struct sdKeyCommand;

/* 814 */
struct mapSpawnData_t;

/* 815 */
struct sdNetTask_DemonWare_SignInDedicated;

/* 816 */
struct bdListFilesResult;

/* 817 */
struct idAASFile;

/* 818 */
struct sdDeclSurfaceTypeMap::sdSurfaceTypeAreaRect;

/* 819 */
struct idCVarCallback_UseMegaTextureImageCompression;

/* 820 */
struct sdDeviceMappingCallback;

/* 821 */
struct idAASFileManagerLocal;

/* 822 */
struct bdNATTravClient;

/* 823 */
struct bdConnectionStore;

/* 824 */
struct bdSequenceNumber;

/* 825 */
typedef struct tagRAWINPUTDEVICE RAWINPUTDEVICE;

/* 826 */
struct tagRAWINPUTDEVICE
{
  USHORT usUsagePage;
  USHORT usUsage;
  DWORD dwFlags;
  HWND hwndTarget;
};

/* 827 */
typedef struct _XINPUT_STATE XINPUT_STATE;

/* 830 */
struct _XINPUT_GAMEPAD
{
  WORD wButtons;
  BYTE bLeftTrigger;
  BYTE bRightTrigger;
  SHORT sThumbLX;
  SHORT sThumbLY;
  SHORT sThumbRX;
  SHORT sThumbRY;
};

/* 829 */
typedef struct _XINPUT_GAMEPAD XINPUT_GAMEPAD;

/* 828 */
struct _XINPUT_STATE
{
  DWORD dwPacketNumber;
  XINPUT_GAMEPAD Gamepad;
};

/* 831 */
typedef struct _XINPUT_CAPABILITIES XINPUT_CAPABILITIES;

/* 834 */
struct _XINPUT_VIBRATION
{
  WORD wLeftMotorSpeed;
  WORD wRightMotorSpeed;
};

/* 833 */
typedef struct _XINPUT_VIBRATION XINPUT_VIBRATION;

/* 832 */
struct _XINPUT_CAPABILITIES
{
  BYTE Type;
  BYTE SubType;
  WORD Flags;
  XINPUT_GAMEPAD Gamepad;
  XINPUT_VIBRATION Vibration;
};

/* 835 */
union __declspec(align(16)) __m128i
{
  __int8 m128i_i8[16];
  __int16 m128i_i16[8];
  __int32 m128i_i32[4];
  __int64 m128i_i64[2];
  unsigned __int8 m128i_u8[16];
  unsigned __int16 m128i_u16[8];
  unsigned __int32 m128i_u32[4];
  unsigned __int64 m128i_u64[2];
};

/* 836 */
union __declspec(align(8)) __m64
{
  unsigned __int64 m64_u64;
  float m64_f32[2];
  __int8 m64_i8[8];
  __int16 m64_i16[4];
  __int32 m64_i32[2];
  __int64 m64_i64;
  unsigned __int8 m64_u8[8];
  unsigned __int16 m64_u16[4];
  unsigned __int32 m64_u32[2];
};

